# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('saf-example', ['saf'])
    obj.source = [
        'nsutil.cc',
        'saf-example.cc',
        'simulation-params.cc',
        ]
